# Projeto Semantix — Modelagem

## Objetivo

Nesta etapa, serão construídos modelos de Machine Learning para investigar a ocorrência de inadimplência.

Os modelos serão treinados utilizando os dados preparados na etapa anterior, mantendo a separação entre dados de treino e teste.

## Modelos

Serão utilizados diferentes modelos para comparar abordagens de modelagem e identificar quais apresentam melhor capacidade de previsão:

- Regressão Linear;
- Duelo de modelos com Cross Validation;
- Decision Tree;
- XGBoost.

## Estratégia

Os modelos serão treinados inicialmente com os dados de treino. A comparação e avaliação de desempenho serão realizadas posteriormente, na etapa de avaliação.

# Bibliotecas -

In [37]:

import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

from sklearn.model_selection import cross_val_score

# Carregando Dataset

In [38]:
# Carregar os dados preparados

X_train = pd.read_csv("../data/X_train.csv")
X_test = pd.read_csv("../data/X_test.csv")
y_train = pd.read_csv("../data/y_train.csv").squeeze()
y_test = pd.read_csv("../data/y_test.csv").squeeze()

# Regressão Linear

In [39]:
# Criar o modelo de Regressão Linear
linear_model = LinearRegression()

# Treinar o modelo
linear_model.fit(X_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [40]:
# Gerar previsões da Regressão Linear
y_pred_linear = linear_model.predict(X_test)

y_pred[:10]

array([ 0.06189876,  0.65808807,  0.18258174,  0.70943305,  0.0644725 ,
        0.28405564, -0.05580149,  0.06922217, -0.0124153 , -0.13368846])

A Regressão Linear foi utilizada como modelo de referência, porém suas previsões apresentaram valores contínuos, incluindo valores negativos e superiores ao intervalo esperado para loan_status (0 ou 1). Isso evidencia uma limitação da aplicação desse modelo a um problema de classificação e reforça a necessidade de comparar seu desempenho com modelos desenvolvidos especificamente para classificação, como Decision Tree e XGBoost.

# Árvore de Decisão

In [41]:
# Criar o modelo de Árvore de Decisão
tree_model = DecisionTreeClassifier(random_state=42)

# Treinar o modelo
tree_model.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [42]:
# Gerar previsões
y_pred_tree = tree_model.predict(X_test)
y_pred_tree[:10]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

# XGBoost

In [43]:
# Criar o modelo XGBoost
xgb_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

# Treinar o modelo
xgb_model.fit(X_train, y_train)

,objective,'binary:logistic'
,base_score,None
,booster,None
,callbacks,None
,colsample_bylevel,None
,colsample_bynode,None
,colsample_bytree,None
,device,None
,early_stopping_rounds,None
,enable_categorical,True
,eval_metric,'logloss'


In [44]:
# Gerar previsões
y_pred_xgb = xgb_model.predict(X_test)
y_pred_xgb[:10]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

# Cross Validation 

In [45]:
# Cross Validation com 5 folds

tree_cv = cross_val_score(
    tree_model,
    X_train,
    y_train,
    cv=5,
    scoring="accuracy"
)

xgb_cv = cross_val_score(
    xgb_model,
    X_train,
    y_train,
    cv=5,
    scoring="accuracy"
)

In [46]:
# Resultados do Cross Validation
print("Decision Tree:", tree_cv)
print("XGBoost:", xgb_cv)

Decision Tree: [0.89217191 0.89351497 0.88775902 0.90234075 0.88696987]
XGBoost: [0.94013814 0.93284728 0.93150422 0.93726017 0.93801574]


In [47]:
# Média da acurácia nos 5 folds
print("Média Decision Tree:", tree_cv.mean())
print("Média XGBoost:", xgb_cv.mean())

Média Decision Tree: 0.8925513035253807
Média XGBoost: 0.9359531088156541


# Conclusão - 

Os modelos foram treinados e comparados inicialmente por meio do Cross Validation. A Decision Tree apresentou acurácia média de 89,3%, enquanto o XGBoost alcançou 93,6%, indicando melhor desempenho médio do XGBoost nessa etapa.

A Regressão Linear foi utilizada como modelo de referência, mas apresentou limitações por se tratar de um problema de classificação. A avaliação final dos modelos será realizada na próxima etapa, considerando outras métricas além da acurácia.