# Projeto Semantix — Avaliação dos Modelos

## Objetivo

Nesta etapa, os modelos desenvolvidos anteriormente serão avaliados utilizando os dados de teste.

Serão utilizadas métricas de classificação para comparar o desempenho dos modelos e identificar qual apresentou melhor capacidade de prever a ocorrência de inadimplência.

## Métricas

Serão analisadas:

- Acurácia;
- Precisão;
- Recall;
- F1-score;
- Matriz de confusão;
- ROC-AUC.

A análise dessas métricas permitirá uma comparação mais adequada entre os modelos, considerando também a distribuição desigual da variável `loan_status`.

# Bibliotecas - 

In [44]:
import pandas as pd
import numpy as np

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score,
    classification_report
)
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

# Carregando treino e teste - 

In [45]:
# Carregar os dados de treino e teste

X_train = pd.read_csv("../data/X_train.csv")
X_test = pd.read_csv("../data/X_test.csv")

y_train = pd.read_csv("../data/y_train.csv").squeeze()
y_test = pd.read_csv("../data/y_test.csv").squeeze()

# Treinando modelos - 

In [46]:
# Criar os modelos

linear_model = LinearRegression()

tree_model = DecisionTreeClassifier(random_state=42)

xgb_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

# Treinar os modelos

linear_model.fit(X_train, y_train)
tree_model.fit(X_train, y_train)
xgb_model.fit(X_train, y_train)

,objective,'binary:logistic'
,base_score,None
,booster,None
,callbacks,None
,colsample_bylevel,None
,colsample_bynode,None
,colsample_bytree,None
,device,None
,early_stopping_rounds,None
,enable_categorical,True
,eval_metric,'logloss'


In [47]:
# Gerar previsões dos modelos

y_pred_linear = linear_model.predict(X_test)

y_pred_tree = tree_model.predict(X_test)

y_pred_xgb = xgb_model.predict(X_test)

In [48]:
# Transformar as previsões da Regressão Linear em classes

y_pred_linear_class = (y_pred_linear >= 0.5).astype(int)

In [49]:
# Calcular a acurácia dos modelos

accuracy_linear = accuracy_score(y_test, y_pred_linear_class)
accuracy_tree = accuracy_score(y_test, y_pred_tree)
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)

print("Acurácia — Regressão Linear:", accuracy_linear)
print("Acurácia — Decision Tree:", accuracy_tree)
print("Acurácia — XGBoost:", accuracy_xgb)

Acurácia — Regressão Linear: 0.8465080583269379
Acurácia — Decision Tree: 0.8844205679201842
Acurácia — XGBoost: 0.9338449731389102


In [50]:
# Calcular a precisão dos modelos

precision_linear = precision_score(y_test, y_pred_linear_class)
precision_tree = precision_score(y_test, y_pred_tree)
precision_xgb = precision_score(y_test, y_pred_xgb)

print("Precisão — Regressão Linear:", precision_linear)
print("Precisão — Decision Tree:", precision_tree)
print("Precisão — XGBoost:", precision_xgb)

Precisão — Regressão Linear: 0.7773386034255599
Precisão — Decision Tree: 0.7206076618229855
Precisão — XGBoost: 0.9600371747211895


In [51]:
# Calcular o recall dos modelos

recall_linear = recall_score(y_test, y_pred_linear_class)
recall_tree = recall_score(y_test, y_pred_tree)
recall_xgb = recall_score(y_test, y_pred_xgb)

print("Recall — Regressão Linear:", recall_linear)
print("Recall — Decision Tree:", recall_tree)
print("Recall — XGBoost:", recall_xgb)

Recall — Regressão Linear: 0.4152005629838142
Recall — Decision Tree: 0.7677691766361717
Recall — XGBoost: 0.7269528501055594


In [52]:
# Calcular o F1-score dos modelos

f1_linear = f1_score(y_test, y_pred_linear_class)
f1_tree = f1_score(y_test, y_pred_tree)
f1_xgb = f1_score(y_test, y_pred_xgb)

print("F1-score — Regressão Linear:", f1_linear)
print("F1-score — Decision Tree:", f1_tree)
print("F1-score — XGBoost:", f1_xgb)

F1-score — Regressão Linear: 0.5412844036697247
F1-score — Decision Tree: 0.7434412265758092
F1-score — XGBoost: 0.8273928714457349


In [53]:
# Calcular as matrizes de confusão

cm_linear = confusion_matrix(y_test, y_pred_linear_class)
cm_tree = confusion_matrix(y_test, y_pred_tree)
cm_xgb = confusion_matrix(y_test, y_pred_xgb)

print("Matriz de Confusão — Regressão Linear:")
print(cm_linear)

print("\nMatriz de Confusão — Decision Tree:")
print(cm_tree)

print("\nMatriz de Confusão — XGBoost:")
print(cm_xgb)

Matriz de Confusão — Regressão Linear:
[[4925  169]
 [ 831  590]]

Matriz de Confusão — Decision Tree:
[[4671  423]
 [ 330 1091]]

Matriz de Confusão — XGBoost:
[[5051   43]
 [ 388 1033]]


# ROC-AUC

In [54]:
# Calcular as probabilidades para ROC-AUC

y_score_linear = y_pred_linear

y_score_tree = tree_model.predict_proba(X_test)[:, 1]

y_score_xgb = xgb_model.predict_proba(X_test)[:, 1]

In [55]:
# Calcular o ROC-AUC dos modelos

roc_linear = roc_auc_score(y_test, y_score_linear)
roc_tree = roc_auc_score(y_test, y_score_tree)
roc_xgb = roc_auc_score(y_test, y_score_xgb)

print("ROC-AUC — Regressão Linear:", roc_linear)
print("ROC-AUC — Decision Tree:", roc_tree)
print("ROC-AUC — XGBoost:", roc_xgb)

ROC-AUC — Regressão Linear: 0.8540410031036499
ROC-AUC — Decision Tree: 0.8423651536891106
ROC-AUC — XGBoost: 0.9503258514729558


# Reports - 

In [56]:
# Gerar os relatórios de classificação

print("Classification Report — Regressão Linear:")
print(classification_report(y_test, y_pred_linear_class))

print("\nClassification Report — Decision Tree:")
print(classification_report(y_test, y_pred_tree))

print("\nClassification Report — XGBoost:")
print(classification_report(y_test, y_pred_xgb))

Classification Report — Regressão Linear:


              precision    recall  f1-score   support

           0       0.86      0.97      0.91      5094
           1       0.78      0.42      0.54      1421

    accuracy                           0.85      6515
   macro avg       0.82      0.69      0.72      6515
weighted avg       0.84      0.85      0.83      6515


Classification Report — Decision Tree:
              precision    recall  f1-score   support

           0       0.93      0.92      0.93      5094
           1       0.72      0.77      0.74      1421

    accuracy                           0.88      6515
   macro avg       0.83      0.84      0.83      6515
weighted avg       0.89      0.88      0.89      6515


Classification Report — XGBoost:
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      5094
           1       0.96      0.73      0.83      1421

    accuracy                           0.93      6515
   macro avg       0.94      0.86      0.89      6515


### Insight — Avaliação dos modelos

A avaliação dos modelos demonstrou diferenças relevantes em seu desempenho. A Regressão Linear apresentou os resultados mais limitados, principalmente na identificação dos clientes inadimplentes, com recall de 41,52% e F1-score de 54,13%.

A Decision Tree apresentou melhora significativa, alcançando 76,78% de recall para a classe de inadimplência, porém com menor precisão e maior quantidade de falsos positivos.

O XGBoost apresentou o melhor desempenho geral, alcançando 93,38% de acurácia, 96,00% de precisão, 82,74% de F1-score e 95,03% de ROC-AUC. Apesar de seu recall de 72,70% ser inferior ao da Decision Tree, o modelo apresentou um equilíbrio superior entre precisão e identificação dos casos de inadimplência.

Dessa forma, entre os modelos avaliados, o XGBoost apresentou o desempenho mais consistente e foi selecionado como o modelo de melhor desempenho para este conjunto de dados.